<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'Laxap\\BootstrapCore\\Service\\InstallService' => $typo3InstallDir . 'typo3conf/ext/bootstrap_core/Classes/Service/InstallService.php',
);
