<?php
# PackageStates.php

# This file is maintained by TYPO3's package management. Although you can edit it
# manually, you should rather use the extension manager for maintaining packages.
# This file will be regenerated automatically if it doesn't exist. Deleting this file
# should, however, never become necessary if you use the package commands.

return [
    'packages' => [
        'core' => [
            'composerName' => 'typo3/cms-core',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/core/',
            'suggestions' => [],
        ],
        'extbase' => [
            'composerName' => 'typo3/cms-extbase',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/extbase/',
            'suggestions' => [],
        ],
        'fluid' => [
            'composerName' => 'typo3/cms-fluid',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/fluid/',
            'suggestions' => [],
        ],
        'documentation' => [
            'composerName' => 'typo3/cms-documentation',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/documentation/',
            'suggestions' => [],
        ],
        'info' => [
            'composerName' => 'typo3/cms-info',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/info/',
            'suggestions' => [],
        ],
        'info_pagetsconfig' => [
            'composerName' => 'typo3/cms-info-pagetsconfig',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/info_pagetsconfig/',
            'suggestions' => [],
        ],
        'extensionmanager' => [
            'composerName' => 'typo3/cms-extensionmanager',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/extensionmanager/',
            'suggestions' => [],
        ],
        'lang' => [
            'composerName' => 'typo3/cms-lang',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/lang/',
            'suggestions' => [],
        ],
        'setup' => [
            'composerName' => 'typo3/cms-setup',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/setup/',
            'suggestions' => [],
        ],
        'rtehtmlarea' => [
            'composerName' => 'typo3/cms-rtehtmlarea',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/rtehtmlarea/',
            'suggestions' => [
                'setup',
            ],
        ],
        'rsaauth' => [
            'composerName' => 'typo3/cms-rsaauth',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/rsaauth/',
            'suggestions' => [],
        ],
        'saltedpasswords' => [
            'composerName' => 'typo3/cms-saltedpasswords',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/saltedpasswords/',
            'suggestions' => [
                'rsaauth',
            ],
        ],
        'func' => [
            'composerName' => 'typo3/cms-func',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/func/',
            'suggestions' => [],
        ],
        'wizard_crpages' => [
            'composerName' => 'typo3/cms-wizard-crpages',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/wizard_crpages/',
            'suggestions' => [],
        ],
        'wizard_sortpages' => [
            'composerName' => 'typo3/cms-wizard-sortpages',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/wizard_sortpages/',
            'suggestions' => [],
        ],
        'about' => [
            'composerName' => 'typo3/cms-about',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/about/',
            'suggestions' => [],
        ],
        'aboutmodules' => [
            'composerName' => 'typo3/cms-aboutmodules',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/aboutmodules/',
            'suggestions' => [],
        ],
        'backend' => [
            'composerName' => 'typo3/cms-backend',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/backend/',
            'suggestions' => [],
        ],
        'belog' => [
            'composerName' => 'typo3/cms-belog',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/belog/',
            'suggestions' => [],
        ],
        'beuser' => [
            'composerName' => 'typo3/cms-beuser',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/beuser/',
            'suggestions' => [],
        ],
        'context_help' => [
            'composerName' => 'typo3/cms-context-help',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/context_help/',
            'suggestions' => [],
        ],
        'cshmanual' => [
            'composerName' => 'typo3/cms-cshmanual',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/cshmanual/',
            'suggestions' => [],
        ],
        'css_styled_content' => [
            'composerName' => 'typo3/cms-css-styled-content',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/css_styled_content/',
            'suggestions' => [],
        ],
        'felogin' => [
            'composerName' => 'typo3/cms-felogin',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/felogin/',
            'suggestions' => [],
        ],
        'filelist' => [
            'composerName' => 'typo3/cms-filelist',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/filelist/',
            'suggestions' => [],
        ],
        'fluid_styled_content' => [
            'composerName' => 'typo3/cms-fluid-styled-content',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/fluid_styled_content/',
            'suggestions' => [],
        ],
        'form' => [
            'composerName' => 'typo3/cms-form',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/form/',
            'suggestions' => [],
        ],
        'frontend' => [
            'composerName' => 'typo3/cms-frontend',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/frontend/',
            'suggestions' => [],
        ],
        'impexp' => [
            'composerName' => 'typo3/cms-impexp',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/impexp/',
            'suggestions' => [],
        ],
        'install' => [
            'composerName' => 'typo3/cms-install',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/install/',
            'suggestions' => [],
        ],
        'lowlevel' => [
            'composerName' => 'typo3/cms-lowlevel',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/lowlevel/',
            'suggestions' => [],
        ],
        'recordlist' => [
            'composerName' => 'typo3/cms-recordlist',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/recordlist/',
            'suggestions' => [],
        ],
        'recycler' => [
            'composerName' => 'typo3/cms-recycler',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/recycler/',
            'suggestions' => [],
        ],
        'reports' => [
            'composerName' => 'typo3/cms-reports',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/reports/',
            'suggestions' => [],
        ],
        'scheduler' => [
            'composerName' => 'typo3/cms-scheduler',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/scheduler/',
            'suggestions' => [],
        ],
        'sv' => [
            'composerName' => 'typo3/cms-sv',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/sv/',
            'suggestions' => [],
        ],
        'sys_note' => [
            'composerName' => 'typo3/cms-sys-note',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/sys_note/',
            'suggestions' => [],
        ],
        't3editor' => [
            'composerName' => 'typo3/cms-t3editor',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/t3editor/',
            'suggestions' => [],
        ],
        't3skin' => [
            'composerName' => 'typo3/cms-t3skin',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/t3skin/',
            'suggestions' => [],
        ],
        'tstemplate' => [
            'composerName' => 'typo3/cms-tstemplate',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/tstemplate/',
            'suggestions' => [],
        ],
        'viewpage' => [
            'composerName' => 'typo3/cms-viewpage',
            'state' => 'active',
            'packagePath' => 'typo3/sysext/viewpage/',
            'suggestions' => [],
        ],
        'svconnector' => [
            'composerName' => 'cobweb/svconnector',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/svconnector/',
            'suggestions' => [],
        ],
        'external_import' => [
            'composerName' => 'cobweb/external_import',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/external_import/',
            'suggestions' => [],
        ],
        'svconnector_csv' => [
            'composerName' => 'cobweb/svconnector_csv',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/svconnector_csv/',
            'suggestions' => [],
        ],
        'svconnector_feed' => [
            'composerName' => 'cobweb/svconnector_feed',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/svconnector_feed/',
            'suggestions' => [],
        ],
        'news' => [
            'composerName' => 'georgringer/news',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/news/',
            'suggestions' => [],
        ],
        'externalimport_tut' => [
            'composerName' => 'cobweb/externalimport_tut',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/externalimport_tut/',
            'suggestions' => [],
        ],
        'static_info_tables' => [
            'composerName' => 'sjbr/static-info-tables',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/static_info_tables/',
            'suggestions' => [],
        ],
        'sr_feuser_register' => [
            'composerName' => 'sjbr/sr-feuser-register',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/sr_feuser_register/',
            'suggestions' => [],
        ],
        'typo3_forum' => [
            'composerName' => 'mittwald/typo3-forum',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/typo3_forum/',
            'suggestions' => [
                'sr_feuser_register',
            ],
        ],
        'cal' => [
            'composerName' => 'cal',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/cal/',
            'suggestions' => [
                'css_styled_content',
            ],
        ],
        'dce' => [
            'composerName' => 'arminvieweg/dce',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/dce/',
            'suggestions' => [],
        ],
        'mask' => [
            'composerName' => 'mask/mask',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/mask/',
            'suggestions' => [],
        ],
        'powermail' => [
            'composerName' => 'powermail',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/powermail/',
            'suggestions' => [],
        ],
        'pt_extbase' => [
            'composerName' => 'punktde/pt_extbase',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/pt_extbase/',
            'suggestions' => [],
        ],
        'pt_extlist' => [
            'composerName' => 'punktde/pt_extlist',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/pt_extlist/',
            'suggestions' => [],
        ],
        'rss_display' => [
            'composerName' => 'typo3cms/rss_display',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/rss_display/',
            'suggestions' => [],
        ],
        'seo_basics' => [
            'composerName' => 'b13/seo_basics',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/seo_basics/',
            'suggestions' => [],
        ],
        'xml_xpath' => [
            'composerName' => 'xml_xpath',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/xml_xpath/',
            'suggestions' => [],
        ],
        'yag' => [
            'composerName' => 'dl/yag',
            'state' => 'active',
            'packagePath' => 'typo3conf/ext/yag/',
            'suggestions' => [],
        ],
        'adodb' => [
            'composerName' => 'typo3/cms-adodb',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/adodb/',
            'suggestions' => [],
        ],
        'dbal' => [
            'composerName' => 'typo3/cms-dbal',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/dbal/',
            'suggestions' => [],
        ],
        'feedit' => [
            'composerName' => 'typo3/cms-feedit',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/feedit/',
            'suggestions' => [],
        ],
        'filemetadata' => [
            'composerName' => 'typo3/cms-filemetadata',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/filemetadata/',
            'suggestions' => [],
        ],
        'indexed_search' => [
            'composerName' => 'typo3/cms-indexed-search',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/indexed_search/',
            'suggestions' => [],
        ],
        'indexed_search_mysql' => [
            'composerName' => 'typo3/cms-indexed-search-mysql',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/indexed_search_mysql/',
            'suggestions' => [],
        ],
        'linkvalidator' => [
            'composerName' => 'typo3/cms-linkvalidator',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/linkvalidator/',
            'suggestions' => [],
        ],
        'opendocs' => [
            'composerName' => 'typo3/cms-opendocs',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/opendocs/',
            'suggestions' => [],
        ],
        'sys_action' => [
            'composerName' => 'typo3/cms-sys-action',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/sys_action/',
            'suggestions' => [],
        ],
        'taskcenter' => [
            'composerName' => 'typo3/cms-taskcenter',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/taskcenter/',
            'suggestions' => [
                'sys_action',
            ],
        ],
        'version' => [
            'composerName' => 'typo3/cms-version',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/version/',
            'suggestions' => [],
        ],
        'workspaces' => [
            'composerName' => 'typo3/cms-workspaces',
            'state' => 'inactive',
            'packagePath' => 'typo3/sysext/workspaces/',
            'suggestions' => [],
        ],
    ],
    'version' => 4,
];
